### Получение списка статей
GET http://localhost:3000/api/articles

### Получение статьи по ID
GET http://localhost:3000/api/articles/tPKz68

### Создание статьи
POST http://localhost:3000/api/articles
Content-Type: application/json

{
  "title":"Как начать программировать",
  "createdDate":"2020-03-29 16:50:32",
  "announce":"Помните, небольшое количество ежедневных упражнений лучше, чем один раз, но много. Простые ежедневные упражнения помогут достичь успеха. Золотое сечение — соотношение двух величин, гармоническая пропорция. Процессор заслуживает особого внимания. Он обязательно понравится геймерам со стажем. Этот смартфон — настоящая находка. Большой и яркий экран, мощнейший процессор — всё это в небольшом гаджете.",
  "fullText":"Скалолазание для нас – это часть жизни. Это не только спорт. Первая большая ёлка была установлена только в 1938 году. Вы можете достичь всего. Стоит только немного постараться и запастись книгами. Это один из лучших рок-музыкантов. Скалолазание для нас – это часть жизни. Это не только спорт. Программировать не настолько сложно, как об этом говорят. Бороться с прокрастинацией несложно. Просто действуйте. Маленькими шагами. Достичь успеха помогут ежедневные повторения. Первая большая ёлка была установлена только в 1938 году. Рок-музыка всегда ассоциировалась с протестами. Так ли это на самом деле? Собрать камни бесконечности легко, если вы прирожденный герой.",
  "сategory":["Туризм","Программирование","Деревья","Рисование","Музыка"]
}

### Редактирование статьи
PUT http://localhost:3000/api/articles/x97Zwl
Content-Type: application/json

{
  "title":"Как закончить программировать",
  "createdDate":"2020-03-29 16:50:32",
  "announce":"Помните, небольшое количество ежедневных упражнений лучше, чем один раз, но много. Простые ежедневные упражнения помогут достичь успеха. Золотое сечение — соотношение двух величин, гармоническая пропорция. Процессор заслуживает особого внимания. Он обязательно понравится геймерам со стажем. Этот смартфон — настоящая находка. Большой и яркий экран, мощнейший процессор — всё это в небольшом гаджете.",
  "fullText":"Скалолазание для нас – это часть жизни. Это не только спорт. Первая большая ёлка была установлена только в 1938 году. Вы можете достичь всего. Стоит только немного постараться и запастись книгами. Это один из лучших рок-музыкантов. Скалолазание для нас – это часть жизни. Это не только спорт. Программировать не настолько сложно, как об этом говорят. Бороться с прокрастинацией несложно. Просто действуйте. Маленькими шагами. Достичь успеха помогут ежедневные повторения. Первая большая ёлка была установлена только в 1938 году. Рок-музыка всегда ассоциировалась с протестами. Так ли это на самом деле? Собрать камни бесконечности легко, если вы прирожденный герой.",
  "сategory":["Туризм","Программирование","Деревья","Рисование","Музыка"]
}

### Удаление статьи по ID
DELETE http://localhost:3000/api/articles/sPhWGz

### Получение списка категорий
GET http://localhost:3000/api/categories

### Получение списка комментариев
GET http://localhost:3000/api/articles/tPKz68/comments

### Создать комментарий
POST http://localhost:3000/api/articles/tPKz68/comments
Content-Type: application/json

{
  "text": "Уже бегу учить китайский!"
}

### Удалить коммент
DELETE http://localhost:3000/api/articles/tPKz68/comments/So7Xyz

### Поиск по названию
GET http://localhost:3000/api/search?query=20-века